// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectCardById = `-- name: SelectCardById :one
SELECT card_id, name, type_id, hr_type_id, frame_id, description, race_id, attribute_id, archetype_id, atk, def, level, scale, linkval, cardmarket_price, tcgplayer_price, ebay_price, amazon_price, coolstuffinc_price, last_import_at FROM cards WHERE cards.card_id=$1
`

func (q *Queries) SelectCardById(ctx context.Context, cardID int32) (Card, error) {
	row := q.db.QueryRow(ctx, selectCardById, cardID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.Name,
		&i.TypeID,
		&i.HrTypeID,
		&i.FrameID,
		&i.Description,
		&i.RaceID,
		&i.AttributeID,
		&i.ArchetypeID,
		&i.Atk,
		&i.Def,
		&i.Level,
		&i.Scale,
		&i.Linkval,
		&i.CardmarketPrice,
		&i.TcgplayerPrice,
		&i.EbayPrice,
		&i.AmazonPrice,
		&i.CoolstuffincPrice,
		&i.LastImportAt,
	)
	return i, err
}

const selectUpdatedCardsIds = `-- name: SelectUpdatedCardsIds :many
SELECT cards.card_id FROM cards WHERE cards.last_import_at = $1
`

func (q *Queries) SelectUpdatedCardsIds(ctx context.Context, lastImportAt pgtype.Timestamp) ([]int32, error) {
	rows, err := q.db.Query(ctx, selectUpdatedCardsIds, lastImportAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var card_id int32
		if err := rows.Scan(&card_id); err != nil {
			return nil, err
		}
		items = append(items, card_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBanlistInfo = `-- name: UpsertBanlistInfo :exec
INSERT INTO banlist_info (card_id, ban_tcg, ban_ocg, ban_goat)
VALUES ($1, $2, $3, $4)
ON CONFLICT (card_id) DO UPDATE SET
    ban_tcg = EXCLUDED.ban_tcg,
    ban_ocg = EXCLUDED.ban_ocg,
    ban_goat = EXCLUDED.ban_goat
`

type UpsertBanlistInfoParams struct {
	CardID  int32       `json:"card_id"`
	BanTcg  pgtype.Text `json:"ban_tcg"`
	BanOcg  pgtype.Text `json:"ban_ocg"`
	BanGoat pgtype.Text `json:"ban_goat"`
}

func (q *Queries) UpsertBanlistInfo(ctx context.Context, arg UpsertBanlistInfoParams) error {
	_, err := q.db.Exec(ctx, upsertBanlistInfo,
		arg.CardID,
		arg.BanTcg,
		arg.BanOcg,
		arg.BanGoat,
	)
	return err
}

const upsertCard = `-- name: UpsertCard :exec
INSERT INTO cards (
    card_id, name, type_id, hr_type_id, frame_id, description,
    race_id, attribute_id, archetype_id,
    atk, def, level, scale, linkval,
    cardmarket_price, tcgplayer_price, ebay_price, amazon_price, coolstuffinc_price, last_import_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20
)
ON CONFLICT (card_id) DO UPDATE SET
    name = EXCLUDED.name,
    type_id = EXCLUDED.type_id,
    hr_type_id = EXCLUDED.hr_type_id,
    frame_id = EXCLUDED.frame_id,
    description = EXCLUDED.description,
    race_id = EXCLUDED.race_id,
    attribute_id = EXCLUDED.attribute_id,
    archetype_id = EXCLUDED.archetype_id,
    atk = EXCLUDED.atk,
    def = EXCLUDED.def,
    level = EXCLUDED.level,
    scale = EXCLUDED.scale,
    linkval = EXCLUDED.linkval,
    cardmarket_price = EXCLUDED.cardmarket_price,
    tcgplayer_price = EXCLUDED.tcgplayer_price,
    ebay_price = EXCLUDED.ebay_price,
    amazon_price = EXCLUDED.amazon_price,
    coolstuffinc_price = EXCLUDED.coolstuffinc_price,
    last_import_at = $20
`

type UpsertCardParams struct {
	CardID            int32            `json:"card_id"`
	Name              string           `json:"name"`
	TypeID            int32            `json:"type_id"`
	HrTypeID          int32            `json:"hr_type_id"`
	FrameID           int32            `json:"frame_id"`
	Description       string           `json:"description"`
	RaceID            int32            `json:"race_id"`
	AttributeID       pgtype.Int4      `json:"attribute_id"`
	ArchetypeID       pgtype.Int4      `json:"archetype_id"`
	Atk               pgtype.Int2      `json:"atk"`
	Def               pgtype.Int2      `json:"def"`
	Level             pgtype.Int2      `json:"level"`
	Scale             pgtype.Int2      `json:"scale"`
	Linkval           pgtype.Int2      `json:"linkval"`
	CardmarketPrice   pgtype.Numeric   `json:"cardmarket_price"`
	TcgplayerPrice    pgtype.Numeric   `json:"tcgplayer_price"`
	EbayPrice         pgtype.Numeric   `json:"ebay_price"`
	AmazonPrice       pgtype.Numeric   `json:"amazon_price"`
	CoolstuffincPrice pgtype.Numeric   `json:"coolstuffinc_price"`
	LastImportAt      pgtype.Timestamp `json:"last_import_at"`
}

func (q *Queries) UpsertCard(ctx context.Context, arg UpsertCardParams) error {
	_, err := q.db.Exec(ctx, upsertCard,
		arg.CardID,
		arg.Name,
		arg.TypeID,
		arg.HrTypeID,
		arg.FrameID,
		arg.Description,
		arg.RaceID,
		arg.AttributeID,
		arg.ArchetypeID,
		arg.Atk,
		arg.Def,
		arg.Level,
		arg.Scale,
		arg.Linkval,
		arg.CardmarketPrice,
		arg.TcgplayerPrice,
		arg.EbayPrice,
		arg.AmazonPrice,
		arg.CoolstuffincPrice,
		arg.LastImportAt,
	)
	return err
}

const upsertCardLinkMarker = `-- name: UpsertCardLinkMarker :exec
INSERT INTO card_link_markers (card_id, marker_id)
VALUES ($1, $2)
ON CONFLICT (card_id, marker_id) DO NOTHING
`

type UpsertCardLinkMarkerParams struct {
	CardID   int32 `json:"card_id"`
	MarkerID int32 `json:"marker_id"`
}

func (q *Queries) UpsertCardLinkMarker(ctx context.Context, arg UpsertCardLinkMarkerParams) error {
	_, err := q.db.Exec(ctx, upsertCardLinkMarker, arg.CardID, arg.MarkerID)
	return err
}

const upsertCardSet = `-- name: UpsertCardSet :one
INSERT INTO card_sets (name, code, num_of_cards, tcg_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    code = EXCLUDED.code,
    num_of_cards = EXCLUDED.num_of_cards,
    tcg_date = EXCLUDED.tcg_date
RETURNING set_id
`

type UpsertCardSetParams struct {
	Name       string      `json:"name"`
	Code       string      `json:"code"`
	NumOfCards pgtype.Int4 `json:"num_of_cards"`
	TcgDate    pgtype.Date `json:"tcg_date"`
}

func (q *Queries) UpsertCardSet(ctx context.Context, arg UpsertCardSetParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertCardSet,
		arg.Name,
		arg.Code,
		arg.NumOfCards,
		arg.TcgDate,
	)
	var set_id int32
	err := row.Scan(&set_id)
	return set_id, err
}

const upsertCardSetInfo = `-- name: UpsertCardSetInfo :exec
INSERT INTO card_set_info (card_id, set_id, rarity_id, price)
VALUES ($1, $2, $3, $4)
ON CONFLICT (card_id, set_id, rarity_id) DO UPDATE SET
    price = EXCLUDED.price
`

type UpsertCardSetInfoParams struct {
	CardID   int32          `json:"card_id"`
	SetID    int32          `json:"set_id"`
	RarityID int32          `json:"rarity_id"`
	Price    pgtype.Numeric `json:"price"`
}

func (q *Queries) UpsertCardSetInfo(ctx context.Context, arg UpsertCardSetInfoParams) error {
	_, err := q.db.Exec(ctx, upsertCardSetInfo,
		arg.CardID,
		arg.SetID,
		arg.RarityID,
		arg.Price,
	)
	return err
}
