// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookups.sql

package db

import (
	"context"
)

const upsertArchetype = `-- name: UpsertArchetype :one
INSERT INTO archetypes (archetype) VALUES ($1)
ON CONFLICT (archetype) DO UPDATE SET archetype = EXCLUDED.archetype
RETURNING archetype_id
`

func (q *Queries) UpsertArchetype(ctx context.Context, archetype string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertArchetype, archetype)
	var archetype_id int32
	err := row.Scan(&archetype_id)
	return archetype_id, err
}

const upsertAttribute = `-- name: UpsertAttribute :one
INSERT INTO attributes (attribute) VALUES ($1)
ON CONFLICT (attribute) DO UPDATE SET attribute = EXCLUDED.attribute
RETURNING attribute_id
`

func (q *Queries) UpsertAttribute(ctx context.Context, attribute string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertAttribute, attribute)
	var attribute_id int32
	err := row.Scan(&attribute_id)
	return attribute_id, err
}

const upsertFrame = `-- name: UpsertFrame :one
INSERT INTO frames (frame) VALUES ($1)
ON CONFLICT (frame) DO UPDATE SET frame = EXCLUDED.frame
RETURNING frame_id
`

func (q *Queries) UpsertFrame(ctx context.Context, frame string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertFrame, frame)
	var frame_id int32
	err := row.Scan(&frame_id)
	return frame_id, err
}

const upsertHrType = `-- name: UpsertHrType :one
INSERT INTO hr_types (hr_type) VALUES ($1)
ON CONFLICT (hr_type) DO UPDATE SET hr_type = EXCLUDED.hr_type
RETURNING hr_type_id
`

func (q *Queries) UpsertHrType(ctx context.Context, hrType string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertHrType, hrType)
	var hr_type_id int32
	err := row.Scan(&hr_type_id)
	return hr_type_id, err
}

const upsertLinkMarker = `-- name: UpsertLinkMarker :one
INSERT INTO link_markers (marker) VALUES ($1)
ON CONFLICT (marker) DO UPDATE SET marker = EXCLUDED.marker
RETURNING marker_id
`

func (q *Queries) UpsertLinkMarker(ctx context.Context, marker string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertLinkMarker, marker)
	var marker_id int32
	err := row.Scan(&marker_id)
	return marker_id, err
}

const upsertRace = `-- name: UpsertRace :one
INSERT INTO races (race) VALUES ($1)
ON CONFLICT (race) DO UPDATE SET race = EXCLUDED.race
RETURNING race_id
`

func (q *Queries) UpsertRace(ctx context.Context, race string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertRace, race)
	var race_id int32
	err := row.Scan(&race_id)
	return race_id, err
}

const upsertRarity = `-- name: UpsertRarity :one
INSERT INTO rarities (rarity, code) VALUES ($1, $2)
ON CONFLICT (rarity) DO UPDATE SET code = EXCLUDED.code
RETURNING rarity_id
`

type UpsertRarityParams struct {
	Rarity string `json:"rarity"`
	Code   string `json:"code"`
}

func (q *Queries) UpsertRarity(ctx context.Context, arg UpsertRarityParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertRarity, arg.Rarity, arg.Code)
	var rarity_id int32
	err := row.Scan(&rarity_id)
	return rarity_id, err
}

const upsertType = `-- name: UpsertType :one
INSERT INTO types (type) VALUES ($1)
ON CONFLICT (type) DO UPDATE SET type=EXCLUDED.type
RETURNING type_id
`

func (q *Queries) UpsertType(ctx context.Context, type_ string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertType, type_)
	var type_id int32
	err := row.Scan(&type_id)
	return type_id, err
}
