// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Archetype struct {
	ArchetypeID int32  `json:"archetype_id"`
	Archetype   string `json:"archetype"`
}

type Attribute struct {
	AttributeID int32  `json:"attribute_id"`
	Attribute   string `json:"attribute"`
}

type BanlistInfo struct {
	CardID  int32       `json:"card_id"`
	BanTcg  pgtype.Text `json:"ban_tcg"`
	BanOcg  pgtype.Text `json:"ban_ocg"`
	BanGoat pgtype.Text `json:"ban_goat"`
}

type Card struct {
	CardID            int32          `json:"card_id"`
	Name              string         `json:"name"`
	TypeID            int32          `json:"type_id"`
	HrTypeID          int32          `json:"hr_type_id"`
	FrameID           int32          `json:"frame_id"`
	Description       string         `json:"description"`
	RaceID            int32          `json:"race_id"`
	AttributeID       pgtype.Int4    `json:"attribute_id"`
	ArchetypeID       pgtype.Int4    `json:"archetype_id"`
	Atk               pgtype.Int2    `json:"atk"`
	Def               pgtype.Int2    `json:"def"`
	Level             pgtype.Int2    `json:"level"`
	Scale             pgtype.Int2    `json:"scale"`
	Linkval           pgtype.Int2    `json:"linkval"`
	CardmarketPrice   pgtype.Numeric `json:"cardmarket_price"`
	TcgplayerPrice    pgtype.Numeric `json:"tcgplayer_price"`
	EbayPrice         pgtype.Numeric `json:"ebay_price"`
	AmazonPrice       pgtype.Numeric `json:"amazon_price"`
	CoolstuffincPrice pgtype.Numeric `json:"coolstuffinc_price"`
}

type CardLinkMarker struct {
	CardID   int32 `json:"card_id"`
	MarkerID int32 `json:"marker_id"`
}

type CardSet struct {
	SetID      int32       `json:"set_id"`
	Name       string      `json:"name"`
	Code       string      `json:"code"`
	NumOfCards pgtype.Int4 `json:"num_of_cards"`
	TcgDate    pgtype.Date `json:"tcg_date"`
}

type CardSetInfo struct {
	CardID   int32          `json:"card_id"`
	SetID    int32          `json:"set_id"`
	RarityID int32          `json:"rarity_id"`
	Price    pgtype.Numeric `json:"price"`
}

type DbVersion struct {
	Version string `json:"version"`
}

type Frame struct {
	FrameID int32  `json:"frame_id"`
	Frame   string `json:"frame"`
}

type HrType struct {
	HrTypeID int32  `json:"hr_type_id"`
	HrType   string `json:"hr_type"`
}

type LinkMarker struct {
	MarkerID int32  `json:"marker_id"`
	Marker   string `json:"marker"`
}

type Race struct {
	RaceID int32  `json:"race_id"`
	Race   string `json:"race"`
}

type Rarity struct {
	RarityID int32  `json:"rarity_id"`
	Rarity   string `json:"rarity"`
	Code     string `json:"code"`
}

type Type struct {
	TypeID int32  `json:"type_id"`
	Type   string `json:"type"`
}

type User struct {
	UserID string `json:"user_id"`
}
