// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: select-random-cards-ids.sql

package db

import (
	"context"
)

const getRandomCardIds = `-- name: GetRandomCardIds :many
SELECT card_id FROM cards
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetRandomCardIds(ctx context.Context, limit int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getRandomCardIds, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var card_id int32
		if err := rows.Scan(&card_id); err != nil {
			return nil, err
		}
		items = append(items, card_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
