// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: version.sql

package db

import (
	"context"
)

const deleteDBVersion = `-- name: DeleteDBVersion :exec
DELETE FROM db_version
`

func (q *Queries) DeleteDBVersion(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteDBVersion)
	return err
}

const getDBVersion = `-- name: GetDBVersion :one
SELECT version FROM db_version LIMIT 1
`

func (q *Queries) GetDBVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getDBVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}

const insertDBVersion = `-- name: InsertDBVersion :exec
INSERT INTO db_version (version) VALUES ($1)
`

func (q *Queries) InsertDBVersion(ctx context.Context, version string) error {
	_, err := q.db.Exec(ctx, insertDBVersion, version)
	return err
}
