FROM docker.angie.software/angie:latest

RUN rm -f /etc/angie/http.d/default.conf

# Copy pre-generated self-signed certs from host
RUN mkdir -p /etc/angie/ssl
COPY ssl/cert.pem /etc/angie/ssl/cert.pem
COPY ssl/key.pem /etc/angie/ssl/key.pem

COPY angie.conf /etc/angie/angie.conf
RUN mkdir /etc/angie/conf.d/
COPY conf.d/ /etc/angie/conf.d/

RUN mkdir -p /var/cache/angie && chown -R angie:angie /var/cache/angie

EXPOSE 80 443

CMD [ "angie", "-g" , "daemon off;" ]
