FROM oven/bun:1.3-alpine AS builder

WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy app files
COPY . .

# Build SvelteKit app (using adapter-node)
RUN bun run build

# ---
FROM oven/bun:1.1-alpine AS runner

WORKDIR /app

# Copy built app and production node_modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

# Environment variables needed for better-auth and drizzle
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

# Start Node adapter via Bun
# CMD ["bun", "run", "build/index.js"]
CMD ["bun", "run" , "dev"]
