FROM golang:alpine as builder

WORKDIR /build
COPY . .
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
#     go build -ldflags="-w -s" -o /app .
run go build -o /app .

FROM gcr.io/distroless/static-debian13
COPY --from=builder /app /bin/app
CMD ["/bin/app"]
