FROM docker.io/library/golang:alpine

WORKDIR /app

# Install dependencies first (for caching)
COPY go.mod go.sum ./
RUN go mod download

# Set the default command to run the code directly instead of building a static binary
CMD ["go", "run", "main.go"]
